export enum RenderIds {
    CALCULATOR_WRAPPER = "CALCULATOR_WRAPPER",

    CALCULATOR_LOADER = "CALCULATOR_LOADER",
    CALCULATOR_ERROR_INDICATOR = "CALCULATOR_ERROR_INDICATOR",

    HISTORY_ELEMENT = "HISTORY_ELEMENT",
    HISTORY_DIALOG = "HISTORY_DIALOG",
    HISTORY_DIALOG_CONTENT = "HISTORY_DIALOG_CONTENT",
    HISTORY_DIALOG_LOADING = "HISTORY_DIALOG_LOADING",
}