export enum RenderIds {
    CALCULATOR_WRAPPER = "CALCULATOR_WRAPPER",

    CALCULATOR_LOADER = "CALCULATOR_LOADER",
    CALCULATOR_ERROR_INDICATOR = "CALCULATOR_ERROR_INDICATOR",

    HISTORY_ELEMENT = "HISTORY_ELEMENT",
}